config/routes.rb
Nessie::Application.routes.draw do

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords"
  }
  devise_for :admins, controllers: {
    sessions: "admins/sessions",
    registrations: "admins/registrations",
    passwords: "admins/passwords"
  }
  namespace :admin do
    resources :users
    resources :admins
    resources :items, except: [:show]
    root 'users#index'
  end
  root 'home#index'

  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :timeoutable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :login
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where([
                                # "lower(username) = :value OR lower(email) = :value",
                                "lower(email) = :value",
                                { value: login.downcase }
                              ]).first
    else
      where(conditions).first
    end
  end

  def self.empty?
    count == 0
  end
end

app/models/item.rb
class Item < ActiveRecord::Base

  belongs_to :user

  validates :name, presence: true

  default_value_for :quantity, 1

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true,
                       uniqueness: { case_sensitive: false },
                       length: { minimum: 6, maximum: 24 },
                       format: { with: /\A[a-zA-Z\d_\.]+\Z/ }

  attr_accessor :login
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where([
                                "lower(username) = :value OR lower(email) = :value",
                                { value: login.downcase }
                              ]).first
    else
      where(conditions).first
    end
  end
end

app/controllers/admin/admins_controller.rb
class Admin::AdminsController < Admin::BaseController
  def index
    @admins = Admin.order(:id).page params[:page]
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!

  def after_sign_out_path_for(resource_or_scope)
    admin_root_path
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < Admin::BaseController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  def index
    @items = Item.all
  end

  # GET /items/1
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to admin_items_url, notice: 'Item was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /items/1
  def update
    if @item.update(item_params)
      redirect_to admin_items_url, notice: 'Item was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /items/1
  def destroy
    @item.destroy
    redirect_to admin_items_url, notice: 'Item was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def item_params
      params.require(:item).permit(:name, :quantity, :user_id)
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def index
    @users = User.order(:username).page params[:page]
  end
end

app/controllers/admins/passwords_controller.rb
class Admins::PasswordsController < Devise::PasswordsController
  layout "devise_admin"
end

app/controllers/admins/registrations_controller.rb
class Admins::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters

  def new
    if Admin.empty?
      super
    else
      redirect_to admin_root_path
    end
  end

  def create
    if Admin.empty?
      super
    else
      redirect_to admin_root_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :email
  end

  def after_sign_up_path_for(resource)
    admin_root_path
  end
end

app/controllers/admins/sessions_controller.rb
class Admins::SessionsController < Devise::SessionsController
  layout "devise_admin"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_admin
    ActiveDecorator::Decorator.instance.decorate(super) unless super.nil?
    super
  end

  def current_user
    ActiveDecorator::Decorator.instance.decorate(super) unless super.nil?
    super
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:email, :username]
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  before_filter :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_in) << :login
  end
end

app/helpers/application_helper.rb
# -*- coding: utf-8 -*-

module ApplicationHelper

  def form_actions(options = {}, &block)
    content_tag :div, class: "form-group" do
      content_tag(:div, class: "col-sm-offset-2 col-sm-6", &block)
    end
  end

  def title(page_title, options={})
    content_for(:title, page_title.to_s)

    icon = options.delete(:icon)
    if icon.blank?
      content_tag :div, class: "row page-header" do
        content_tag :h1 do
          "#{page_title}"
        end
      end
    else
      content_tag :div, class: "row page-header" do
        content_tag :h1 do
          raw "#{fa_icon("user")} #{page_title}"
        end
      end
    end
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="panel panel-danger">
      <div class="panel-heading">#{sentence}</div>
      <div class="panel-body"><ul>#{messages}</ul></div>
    </div>
    HTML

    html.html_safe
  end
end

app/views/admin/admins/index.html.erb
<%= title "管理者一覧", icon: "user" %>
<div class="panel panel-default">
  <div class="panel-heading">管理者一覧</div>
  <table class="table table-bordered table-striped table-hover table-condensed">
    <thead>
      <tr>
        <th>ID</th>
        <th>E-Mail</th>
        <th>CreatedAt</th>
        <th style="width: 40px">&nbsp;</th>
      </tr>
    </thead>
    <tfoot>
    </tfoot>
    <tbody>
      <% @admins.each do |admin| %>
        <tr>
          <td><%= admin.id %></td>
          <td><%= admin.email %></td>
          <td><%= l admin.created_at %></td>
          <td>
            <div class="btn-group">
              <button class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                <%= fa_icon "gear" %>
              </button>
              <ul class="dropdown-menu pull-right">
                <li><a href="#">Show</a></li>
                <li><a href="#">Edit</a></li>
                <li><a href="#">Remove</a></li>
                <li class="divider"></li>
                <li><a href="#">Add</a></li>
              </ul>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <% if @admins.total_pages > 1 %>
    <div class="panel-footer">
      <div class="pull-right">
        <%= paginate @admins %>
      </div>
      <div class="clearfix"></div>
    </div>
  <% end %>
</div>

app/views/admin/items/_form.html.erb
<%= simple_form_for([:admin, @item], html: { class: "form-horizontal"}) do |f| %>

  <%= f.input :name %>
  <%= f.input :quantity %>

  <%= form_actions do %>
    <%= f.button :submit, class: "btn btn-default" %>
  <% end %>
<% end %>

app/views/admin/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_items_path %>

app/views/admin/items/index.html.erb
<h1>Listing items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Quantity</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.quantity %></td>
        <td><%= item.user_id %></td>
        <td><%= link_to 'Edit', edit_admin_item_path(item) %></td>
        <td><%= link_to 'Destroy', [:admin, item], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_admin_item_path %>

app/views/admin/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_items_path %>

app/views/admin/users/index.html.erb
<div class="row page-header">
  <div class="container">
    <h1>
      <%= fa_icon("user") %> ユーザ一覧
    </h1>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">ユーザ一覧</div>
  <table class="table table-bordered table-striped table-hover table-condensed">
    <thead>
      <tr>
        <th>ID</th>
        <th>ユーザー名</th>
        <th>E-Mail</th>
        <th>CreatedAt</th>
        <th style="width: 40px">&nbsp;</th>
      </tr>
    </thead>
    <tfoot>
    </tfoot>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= user.username %></td>
          <td><%= user.email %></td>
          <td><%= l user.created_at %></td>
          <td>
            <div class="btn-group">
              <button class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                <%= fa_icon "gear" %>
              </button>
              <ul class="dropdown-menu">
                <li><a href="#">Show</a></li>
                <li><a href="#">Edit</a></li>
                <li><a href="#">Remove</a></li>
                <li class="divider"></li>
                <li><a href="#">Add</a></li>
              </ul>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="panel-footer">
    <div class="pull-right">
      <%= paginate @users %>
    </div>
    <div class="clearfix"></div>
  </div>
</div>

app/views/admins/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/application/_status.html.erb
          <!-- プロフィール -->
          <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <span>
                  <%= current_user.avatar_link %>
                  <span> <%= current_user.username %> <b class="caret"></b></span>
                </span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to edit_user_registration_path do %>
                    <%= fa_icon :user %>
                    <span>Profile</span>
                  <% end %>
                </li>
                <li>
                  <%= link_to edit_user_password_path do %>
                    <%= fa_icon :gear %> 
                    <span>Settings</span>
                  <% end %>
                </li>
                <li><%= link_to destroy_user_session_path, method: :delete do %>
                    <i class="glyphicon glyphicon-off"></i> 
                    <span>Logout</span>
                  <% end %></li>
              </ul>
            </li>
          </ul>
          <% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :class => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav navbar-nav">
  <%= render 'layouts/navigation_links' %>
</ul>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><%= content_for?(:title) ? yield(:title) : "Admin" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag :application, media: "all", "data-turbolinks-track" => true %>
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>


    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="../../assets/js/html5shiv.js"></script>
      <script src="../../assets/js/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <div class="wrap">
      <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
          <!-- グローバルヘッダー -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse-top">
              <span class="sr-only">Toggle Top Navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>

            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse-side">
              <span class="sr-only">Toggle Side Navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>

            <%= link_to "Admin", root_path, class: "navbar-brand" %>!
          </div>
          
          <div class="navbar-collapse navbar-collapse-top collapse">
            
            <!-- ナビゲーション -->
            <ul class="nav navbar-nav navbar">
              <li class="active"><%= link_to "Home", admin_root_path %></li>
              <li><%= link_to "User", admin_users_path %></li>
              <li><%= link_to "Admin", admin_admins_path %></li>
              <li><%= link_to "Item", admin_items_path %></li>
            </ul>

            <!-- プロフィール -->
            <% if admin_signed_in? %>
              <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <span>
                      <%= current_admin.avatar_link %>
                      <span> <%= current_admin.email %> <b class="caret"></b></span>
                    </span>
                  </a>
                  <ul class="dropdown-menu">
                    <li>
                      <%= link_to edit_admin_registration_path do %>
                        <%= fa_icon :user %>
                        <span>Profile</span>
                      <% end %>
                    </li>
                    <li>
                      <%= link_to edit_admin_password_path do %>
                        <%= fa_icon :gear %> 
                        <span>Settings</span>
                      <% end %>
                    </li>
                    <li><a href="#"><i class="glyphicon glyphicon-envelope"></i> 
                        <span>Messages</span></a></li>
                    <li><%= link_to destroy_admin_session_path, method: :delete do %>
                        <i class="glyphicon glyphicon-off"></i>
                        <span>Logout</span>
                    <% end %></li>
                  </ul>
                </li>
              </ul>
            <% end %>
          </div>
        </div>
      </div>
      
      <div class="primary-sidebar hidden-xs">
        <ul class="nav navbar-collapse navbar-collapse-side collapse">
          
          <li class="">
            <%= link_to admin_root_path do %>
              <i class="icon-dashboard icon-2x"></i>
              <span>Dashboard</span>
            <% end %>
          </li>
          <li class="">
            <%= link_to admin_users_path do %>
              <i class="icon-user icon-2x"></i>
              <span>User</span>
            <% end %>
          </li>
          <li class="">
            <%= link_to admin_admins_path do %>
              <i class="icon-user icon-2x"></i>
              <span>Admin</span>
            <% end %>
          </li>
          <li class="">
            <%= link_to admin_items_path do %>
              <i class="icon-user icon-2x"></i>
              <span>Item</span>
            <% end %>
          </li>
          
        </ul>
      </div> <!-- /primary-sidebar -->

      <div id="main-content">
        <div class="container">
          <%= yield %>
        </div> <!-- /container -->
      </div> <!-- /main-content -->
    </div> <!-- /wrap -->

    <footer class="navbar navbar-default navbar-fixed-bottom">
      <div class="container">
        <p class="navbar-text">&copy; Company 2013</p>
      </div>
    </footer>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Nessie" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Nessie" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header class="navbar navbar-inverse navbar-fixed-top" role="banner">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Nessie", root_path, class: "navbar-brand" %>
        </div>
        <nav class="collapse  navbar-collapse" role="navigation">
          <%= render 'layouts/navigation' %>
          <%= render 'status' %>
        </nav>
      </div>
    </header>
    <main role="main">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Nessie" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Nessie" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top" role="banner">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Nessie", root_path, class: "navbar-brand" %>
        </div>
      </div>
    </header>
    <main role="main">
      <!--
      <%= render 'layouts/messages' %>
      -->
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/devise_admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><%= content_for?(:title) ? yield(:title) : "Admin" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag :application, media: "all", "data-turbolinks-track" => true %>
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>


    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="../../assets/js/html5shiv.js"></script>
      <script src="../../assets/js/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <!-- グローバルヘッダー -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Admin", root_path, class: "navbar-brand" %>
        </div><!--/.navbar-header -->
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= yield %>
        </div>
      </div>

      <hr>
      <footer>
        <p>&copy; Company 2013</p>
      </footer>
    </div> <!-- /container -->

    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  </body>
</html>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>